FROM node:18.13.0-alpine3.17 AS base

FROM base AS deps
WORKDIR /deps
COPY package.json .
RUN apk add --no-cache python3 g++ make git
RUN npm install --arch=arm64 --platform=linuxmusl

FROM --platform=linux/amd64 base AS app
WORKDIR /usr/src/app
COPY --from=deps /deps/node_modules ./node_modules
COPY . .
ENV PORT=8080
EXPOSE 8080
CMD [ "npm", "run", "start:dev" ]
